# Site
repository: Yar-13/Yar-13.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Синегрибов Ярослав Владимирович
title: Junior Data Scientist
email: yvs-work@yandex.ru
# phone: 84950000000
# website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  Yar-13
# stackoverflow_username: 
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
# linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: inf0_hunter
  icon: fab fa-telegram
  url: https://t.me/inf0_hunter
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

additional_links:
- title: YAR2199978
  icon: fab fa-kaggle
  url: https://www.kaggle.com/yar2199978

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: Эпиграф
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  **Summary**

  Начинающий Data Science  специалист.

  Опыт более года.

  Основные инструменты для работы:
  - Python
  - SQL

  > Предпочитаю удалённый формат работы.
  >
  > Зарплатные ожидания: 60 000 - 100 000 при полной занятости.

content:
  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Яндекс Практикум
        link: practicum.yandex.ru/data-scientist
        link_text: practicum.yandex.ru
        caption: 14.03.2024 — 30.06.2025
        sub_title: "Data Scientist plus: Extended Program"
        quote: >
          Яндекс Практикум — образование для качественных изменений в карьере и жизни!
        description: | # this will include new lines to allow paragraphs
          Я прошёл полноценный официальный курс, в результате которого был приобретён необходимый теоретический объём знаний. Кроме того, за время обучения я разработал множество решений в виде учебной проектной деятельности.
      - layout: left
        title: Московский Политех
        caption: 2024 - настоящее время
        sub_title: "Большие и открытые данные"
        description: |
          Я получаю высшее образование в передовом Московском Университете. Полностью заочная форма обучения (онлайн) позволяет ставить в приоритет работу и личные проекты.

  - title: Навыки и опыт # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Навыки
        # sub_title: Senior Network System Administrator
        sub_title: |
          Python, SQL, Git, PostgreSQL, Jupyter Notebook, Scikit-learn, matplotlib, pandas, Numpy, tensorflow, keras, Markdown, CatBoost, LightGBM, Res-Net, PySpark, deepseek
        link: https://github.com/Yar-13/
        link_text: github.com/Yar-13
        description: | # this will include new lines to allow paragraphs
          За время изучения DS сферы выполнил более 20 проектов различной сложности.
          
          В рамках работы над проектами:

          - Проводил обработку и очистку табличных данных, временных рядов, наборов естественного языка и изображений;
          - Исследовал данные, визуализируя различные признаки и показывая закономерности;
          - Разрабатывал модели машинного обучения для классификации и прогнозирования;
          - Применял интепретирование признаков обученной модели и элементы математической статистики;
          - Взаимодействовал с базами данных посредством SQL запросов, используя в том числе оконные функции;
          
          Результаты моей деятельности:

          - Разработал решение для [определения успешности стартапа](https://github.com/Yar-13/Kaggle_competition_StartupOperations);
          - Повысил эффективность работы научной обсерватории за счёт [автоматического определеня температуры звезды](https://github.com/Yar-13/Predicting-the-temperature-of-a-star);
          - Построил [модель для определения прибыльного регина добычи нефти](https://github.com/Yar-13/ML_GeoOilProb);
          - Помог сделать процесс обработки металла более эффективным за счёт предсказания итоговой температуры сплава в ковше.



  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  #         ![](https://pictures.s3.yandex.net/resources/image_-_2024-12-04T131130.634_1733299906.png)

  - title: Обо мне
    layout: list
    content:
      - layout: top-right
        quote: >
          Думать - это прикольно!
        description: |
          Мой интерес к сфере анализа и изучения данных не случайный. Поиск зависимостей и неочевидных суждений, которые может скрывать в себе информация,- это путь к стабильному развитию.

          Изначально в IT я изучал область информационной безопасности и уже успел получить достаточное количество теоретических знаний, однако наука о данных захвтила моё внимание. Поэтому я целенаправленно отчислися из первого университета, в котром был специалитет "Компьютерная безопасность".

          Теперь я учусь на заочном формате в университете по специальности. А, чтобы получить наиболее свежие знания, я  прошёл курс по Data Science.

          Я постоянно стараюсь получать новую информацию, чтобы действовать эффективнее и всегда смотреть на несколько шагов вперёд.

          ![](https://i.pinimg.com/736x/ba/4a/79/ba4a7952f7248e783c95b7ff43ee2771.jpg)


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
