# Site
repository: Yar-13/Yar-13.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Синегрибов Ярослав Владимирович
title: Junior Data Scientist
email: yvs-work@yandex.ru
phone: 84950000000
# website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  Yar-13
# stackoverflow_username: 
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
# linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: inf0_hunter
  icon: telegram
  url: https://t.me/inf0_hunter
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: Эпиграф
about_profile_image: images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Начинающий Data Science  специалист.

  Основные инструменты для работы:
  - Python
  - SQl

  > Предпочитаю удалённый формат работы.
  > Зарплатные ожидания: 60 000 - 100 000 при полной занятости.

content:
  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Яндекс Практикум
        caption: 2024 - 2025
        sub_title: "Data Scientist plus: Extended Program"
        quote: >
          Яндекс Практикум — образование для качественных изменений в карьере и жизни!
        description: | # this will include new lines to allow paragraphs
          Я прошёл полноценный официальный курс, в результате которого был приобретён необходимый теоретический объём знаний. Кроме того, за время обучения я разработал множество решений в виде учебной проектной деятельности.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: list
    content:
      layout: top-middle
      description: | # this will include new lines to allow paragraphs
        Alongside my interests in networks and software engineering some of my other interests and hobbies are:
        - Rock climbing
        - Gaming
        - Knitting
        - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

        Look at this cool image  
        ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
